apexx-refresh-2024/force-app/main/default/objects/Pagghiazzu__c/Pagghiazzu__c.object-meta.xml
<CustomObject>
    <description>A random object used to test sharing</description>
    <label>Pagghiazzu</label>
    <nameField>
        <label>Pagghiazzu Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pagghiazzi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apexx-refresh-2024/force-app/main/default/objects/Pagghiazzu__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

apexx-refresh-2024/force-app/main/default/classes/PagghiazzuController.cls
public without sharing class PagghiazzuController {

    @AuraEnabled
    public static List<Pagghiazzu__c> getPagghiazzi() {
        try {
            // AuraEnabled methods default to WITH_SHARING ONLY when no sharing condition is specified at class level
            return [SELECT Id, Name, Color__c, OwnerId FROM Pagghiazzu__c]; // CWE 284
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}