apexx-refresh-2024/force-app/main/default/objects/Pagghiazzu__c/Pagghiazzu__c.object-meta.xml
<CustomObject>
    <description>A random object used to test sharing</description>
    <label>Pagghiazzu</label>
    <nameField>
        <label>Pagghiazzu Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pagghiazzi</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apexx-refresh-2024/force-app/main/default/objects/Pagghiazzu__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

apexx-refresh-2024/force-app/main/default/classes/PagghiazzuWithoutSharingController.cls
public without sharing class PagghiazzuWithoutSharingController {

    @AuraEnabled
    public static List<Pagghiazzu__c> getPagghiazzi() {
        try {
            // AuraEnabled methods default to WITH_SHARING when no sharing condition is specified at class level
            // from release Spring '21. Before Spring'21 they were defaulting to no sharing.
            // In this example the class is specifying "without sharing", in which case "without sharing" is enforced
            List<Pagghiazzu__c> p = [SELECT Id, Name, Color__c, OwnerId FROM Pagghiazzu__c with USER_MODE];     // FP 284
            List<Pagghiazzu__c> p2 = [SELECT Id, Name, Color__c, OwnerId FROM Pagghiazzu__c with SYSTEM_MODE];  // CWE 284
            return [SELECT Id, Name, Color__c, OwnerId FROM Pagghiazzu__c];                                     // CWE 284
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}